/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SolutionTest {
    @Test
    void solution(){
        Solution solution = new Solution();
        String[] participant = new String[]{"leo","kiki","eden"};
        String[] completion = new String[]{"eden","kiki"};

        assertEquals("leo",solution.solution(participant,completion));
    }
}
