/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.IntStream;
public class Application {
    public int solution(int n, int[] lost, int[] reserve) {
        int count = 0;
        Arrays.sort(lost);
        Arrays.sort(reserve);
        for (int i = 0; i < lost.length; i++) {
            for (int j = 0; j < reserve.length; j++) {
                if (lost[i] == reserve[j]) {
                    lost[i] = -1;
                    reserve[j] = -1;
                    count++;
                    break;
                }
            }
        }
        for (int i = 0; i < lost.length; i++) {
            for (int j = 0; j < reserve.length; j++) {
                if (lost[i] == reserve[j] + 1 || lost[i] == reserve[j] - 1) {
                    count++;
                    reserve[j] = -1;
                    break;

                }
            }
        }
        return n - lost.length + count;

    }
}

//    public int solution(int n, int[] lost, int[] reserve) {
//        int answer = n - lost.length;
//
//        for (int i = 0; i < lost.length; i += 1) {
//            for (int j = 0; j < reserve.length; j += 1) {
//                if (lost[i] == reserve[j]) {
//                    reserve[j] = -1;
//                    lost[i] = -1;
//                    answer += 1;
//                    break;
//                }
//            }
//        }
//
//        for (int i = 0; i < lost.length; i += 1) {
//            for (int j = 0; j < reserve.length; j += 1) {
//                if (lost[i] == reserve[j] - 1 || lost[i] == reserve[j] + 1) {
//                    reserve[j] = -1;
//                    answer += 1;
//                    break;
//                }
//            }
//        }
//
//        return answer;
//    }
