/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Solution;

import org.junit.jupiter.api.Test;

class SolutionTest {
    @Test void appHasAGreeting() {
        Solution classUnderTest = new Solution();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
