/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    public List<Integer> solution(int[] array, int[][] commands) {
        //준비
        List<Integer> answer = new ArrayList<>();

        //입력

        //처리

        for (int[] command : commands) {
            int i = command[0];
            int j = command[1];
            int k = command[2];

            array = Arrays.copyOfRange(array, i - 1, j);

            Arrays.sort(array);

            int pick = array[k - 1];

            answer.add(pick);
        }

        //출력
        return answer;
    }
}
