/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package 자릿수더하기;

public class Application {
    public int solution(int n) {
        int answer = 0;
        String numberToString = "" + n;
        String[] array = numberToString.split("");
        for (int i = 0; i < numberToString.length();i+=1) {
            answer +=Integer.parseInt(array[i]);
        }
        return answer;
    }
}
