/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solution;

import java.util.Arrays;

public class Solution {
    public String solution(String[] participant, String[] completion) {
        Arrays.sort(participant);  // 참가자 명단을 정렬
        Arrays.sort(completion);   // 완주자 명단을 정렬

        // 두 명단을 비교하면서 완주하지 못한 선수를 찾음
        int i;
        for (i = 0; i < completion.length; i++) {
            if (!participant[i].equals(completion[i])) {
                return participant[i];
            }
        }

        // 마지막 참가자가 완주하지 못한 경우 처리
        return participant[i];
    }
}

