/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberofdivisorandaddition;

import java.util.ArrayList;
import java.util.List;

public class Solution {
    public int solution(int left, int right) {
        int answer = 0;
        int divisor = 0;
        int result = 0;
        for (int i = left; i <= right; i += 1) {
            for (int k = 1; k <= i; k += 1) {
                if (i % k == 0) {
                    divisor += 1;
                }
            }
            if (divisor % 2 == 0) {
                result += i;
            }
            if (divisor % 2 != 0) {
                result -= i;
            }
            divisor = 0;
            answer = result;
        }
        return answer;
    }
}
