/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package budget;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void solution() {
        App app = new App();

        assertEquals(3, app.solution(new int[]{1, 3, 2, 5, 4}, 9));

    }
}
