/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package 자릿수더하기;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApplicationTest {
    @Test
    void test(){
        Application application = new Application();
        assertEquals(6,application.solution(123));
    }
}
