/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package failurerate;

import java.util.ArrayList;
import java.util.List;

public class Solution {
    public int[] solution(int N, int[] stages) {
        int[] answer = {};
        List<Integer> repository = new ArrayList<>();
        for (int i = 1; i <= N; i += 1) {
            for (int j = 1; j <= stages.length; i += 1) {
                if (stages[j] == i) {
                    repository.add(stages[j]);

                }
            }
        }

        return answer;
    }
}
